/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package comicportascrapper;

import java.awt.List;
import java.io.IOException;
import java.io.PrintStream;
import java.io.UnsupportedEncodingException;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.SwingWorker;
import javax.swing.table.DefaultTableModel;
import org.jsoup.Jsoup;
import org.jsoup.nodes.Document;
import org.jsoup.nodes.Element;

/**
 *
 * @author Ryan
 */
public class mainJFrame extends javax.swing.JFrame {

    
    /**
     * Creates new form mainJFrame
     */
    public mainJFrame() {
        initComponents();
        ImageIcon logo = new ImageIcon(getClass().getResource("icon.png"));
        this.setIconImage(logo.getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mangaJComboBox = new javax.swing.JComboBox<>();
        mangaJButton = new javax.swing.JButton();
        notificationJLabel = new javax.swing.JLabel();
        statusLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mangaJComboBox.setFont(new java.awt.Font("MS Gothic", 0, 12)); // NOI18N
        mangaJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mangaJComboBoxActionPerformed(evt);
            }
        });

        mangaJButton.setFont(new java.awt.Font("MS Gothic", 0, 12)); // NOI18N
        mangaJButton.setText("Go to manga");
        mangaJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mangaJButtonActionPerformed(evt);
            }
        });

        notificationJLabel.setFont(new java.awt.Font("MS Gothic", 0, 12)); // NOI18N
        notificationJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        notificationJLabel.setText("Select a Series (Opening may take a while)");

        statusLabel.setFont(new java.awt.Font("MS Gothic", 0, 12)); // NOI18N
        statusLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(statusLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(notificationJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(mangaJComboBox, 0, 301, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(mangaJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(notificationJLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mangaJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mangaJButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(statusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    ArrayList<String> links = new ArrayList<>();
    
    private void mangaJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mangaJComboBoxActionPerformed
        
    }//GEN-LAST:event_mangaJComboBoxActionPerformed

    private void mangaJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mangaJButtonActionPerformed
        mangaJButton.setEnabled(false);
        statusLabel.setText("Opening series...");
        
        SwingWorker<Void, Void> worker = new SwingWorker<>(){
            @Override
            protected Void doInBackground() throws Exception {
                int index = mangaJComboBox.getSelectedIndex();
                System.out.printf("\n----Opening: %s", links.get(index));

                mangaJFrame chapter = new mangaJFrame();
                chapter.openMangaSite(links.get(index));
                chapter.setLocationRelativeTo(null);
                chapter.setVisible(true);
                return null;
            }
            
            @Override
            protected void done(){
                dispose();
            }
        };
        worker.execute();
    }//GEN-LAST:event_mangaJButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainJFrame().setVisible(true);
            }
        });
    }
    
    public void onStartUp(){
        
        final String url =
                "https://comic-porta.com/series/";
        try{
            final Document document = Jsoup.connect(url).get();
            
            for (Element manga : document.select(
            "h3.title")){
                String title = manga.text();
                String link = manga.select("h3 > a").attr("href");
                
                System.out.printf("Inserting: %s (%s)\n",
                        title, link);
                mangaJComboBox.addItem(title);
                links.add(link);
            }
            
        }
        catch(IOException ex){
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton mangaJButton;
    private javax.swing.JComboBox<String> mangaJComboBox;
    private javax.swing.JLabel notificationJLabel;
    private javax.swing.JLabel statusLabel;
    // End of variables declaration//GEN-END:variables
}
